[package]
name = "gnx-setup"
version.workspace = true
edition.workspace = true

[dependencies]
gnx-control-protocol = { path = "../../crates/control-protocol" }
serde_json.workspace = true
serde.workspace = true
uuid.workspace = true

[target.'cfg(windows)'.dependencies]
tao = "0.30"
wry = "0.49"
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }
